Collections
ElvisBekis/Codelex-exercises pull request #9
Opened 2022-03-26 18:28 UTC by ElvisBekis

2022-04-10 12:08 UTC, NilsKula requested changes

2022-04-10 12:08 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneEntry.java
> +    String name;
private

2022-04-10 12:08 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneEntry.java
> +    String name;
private

2022-04-10 12:08 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/Exercise4.java
> +        String name = null;
labāk nepiešķirt `null` sākumā

2022-04-10 12:08 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/FlightPlanner.java
> +    private static final List<String> route = new ArrayList<>();
caps constants

2022-04-10 12:08 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/FlightPlanner.java
> +                getCityList().forEach(System.out::println);
šo lielo else bloku vismaz uz kādu palīgmetodi

2022-04-10 12:08 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/WordCount.java
> +        for (String line : lines) {
`int numOfWords = numOfWords(lines)` 
būtu pavisam skaisti
vienkārši lai izlaistu tādu setošanu uz 0 un tad pēctam pieškirot vērtību pa jaunam

2022-04-13 13:48 UTC, merged

2022-04-15 18:00 UTC, NilsKula reviewed
all good, tik turpmāk nemergo bez approve, otherwise all this process looses purpose 😄

2022-04-15 20:14 UTC, ElvisBekis commented
> all good, tik turpmāk nemergo bez approve, otherwise all this process looses purpose 😄

Es jau domāju, tas tāds sīkums bija, tāpēc ar nomerdžoju, bet nu ņemšu vērā!